spring:
  h2:
    console:
      enabled: true
  config:
    import: optional:configserver:http://localhost:7777
  datasource:
    url: jdbc:h2:mem:users;
    username: sa
    password: sa
    driver-clas-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
      show-sql: true
  jwt:
    secret: 9a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c8b5f6v8a3d9
